openapi: 3.0.0
info:
  title: Trails API
  description: An API to manage trails, their features, activities, and related data, with authentication.
  version: "1.0.0"
servers:
  - url: http://127.0.0.1:5000
    description: Local server
paths:
  /login:
    post:
      summary: Authenticate a user
      description: Login a user using their credentials.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "your_username"
                password:
                  type: string
                  example: "your_password"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  username:
                    type: string
        "401":
          description: Authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /trails:
    get:
      summary: Get a list of trails
      parameters:
        - name: page
          in: query
          required: false
          description: Page number for pagination.
          schema:
            type: integer
            default: 1
        - name: per_page
          in: query
          required: false
          description: Number of items per page.
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        TrailID:
                          type: integer
                        TrailName:
                          type: string
                        TrailDifficulty:
                          type: string
                        TrailDistance:
                          type: number
                          format: float
                        TrailEstTime:
                          type: string
                        TrailRouteType:
                          type: string
                        TrailDescription:
                          type: string
                        LocationID:
                          type: integer
                  total:
                    type: integer
                  page:
                    type: integer
                  pages:
                    type: integer
        "500":
          description: Internal Server Error
    post:
      summary: Create a new trail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                TrailName:
                  type: string
                  example: "Beautiful Trail"
                TrailDifficulty:
                  type: string
                  example: "Easy"
                TrailDistance:
                  type: number
                  example: 5.2
                TrailEstTime:
                  type: string
                  example: "01h 30m"
                TrailRouteType:
                  type: string
                  example: "Loop"
                TrailRating:
                  type: number
                  example: "4.5"
                TrailDescription:
                  type: string
                  example: "A scenic trail perfect for beginners."
                LocationID:
                  type: integer
                  example: 1
      responses:
        "201":
          description: Trail created successfully
        "400":
          description: Bad Request
  /trails/{trail_id}:
    get:
      summary: Get details of a specific trail
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful response
        "404":
          description: Trail not found
    put:
      summary: Update a specific trail
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                TrailName:
                  type: string
                TrailRating:
                  type: number
                TrailDifficulty:
                  type: string
                TrailDistance:
                  type: number
                TrailEstTime:
                  type: string
                TrailRouteType:
                  type: string
                TrailDescription:
                  type: string
                LocationID:
                  type: integer
      responses:
        "200":
          description: Trail updated successfully
        "400":
          description: Bad Request
        "404":
          description: Trail not found
    delete:
      summary: Delete a specific trail
      parameters:
        - name: trail_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Trail deleted successfully
        "404":
          description: Trail not found
  /logout:
      post:
        summary: Log out the current user
        description: Clears the session and logs out the user.
        responses:
          "200":
            description: Logout successful
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: "Logged out successfully."
          "500":
            description: Internal Server Error
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
                      example: "Internal Server Error"